%RTWMAKECFG adds include and source directories to rtw make files.
%  
%  This file was autmomatic generated by dSPACE Blockset
%  To include the RTI-Sources to the RTW-Build-Prozess the path to this
%  file has to be part of the matlab-search-path
%  
%   See also RTWMAKECFG, MAKE_RTW, PATH.
%  
%  Copyright 2020 by dSPACE GmbH. All rights reserved.
%  
function makeInfo = rtwmakecfg()

makeInfo.includePath = {'', cd};
makeInfo.sourcePath  = {'', cd};
                                                                   
StaticSourceDir = which('dsRTICANMMGlobals.h');                  
if ~isempty(StaticSourceDir)                                       
  makeInfo.includePath{end+1} = fileparts(StaticSourceDir);        
end
                                                              
Type = rtimmsu_private('fcnlib', 'rttype', bdroot(gcs));       
if (strcmp(Type, 'DSOFFSIM'))                                    
    StaticSourceDir = which('dsstd.h');                          
    if ~isempty(StaticSourceDir)                                   
      makeInfo.includePath{end+1} = fileparts(StaticSourceDir);    
    end                                                            
                                                                   
    StaticSourceDir = which('dscan.h');                          
    if ~isempty(StaticSourceDir)                                   
      makeInfo.includePath{end+1} = fileparts(StaticSourceDir);    
    end                                                            
                                                                   
    StaticSourceDir = which('DsJ1939Node.h');                    
    if ~isempty(StaticSourceDir)                                   
      makeInfo.includePath{end+1} = fileparts(StaticSourceDir);    
    end                                                            
    StaticSourceDir = which('DSJ1939_Host');                     
    if ~isempty(StaticSourceDir)                                   
      makeInfo.linkLibsObjs{1} = StaticSourceDir;                  
    end                                                            
                                                                   
    StaticSourceDir = which('dscan');                            
    if ~isempty(StaticSourceDir)                                   
      makeInfo.linkLibsObjs{end+1} = StaticSourceDir;              
    end                                                            
end                                                                
                                                                   
if (strcmpi(Type, 'RTI1006'))                                                                               
    makeInfo.linkLibsObjs = {...                                                                              
        sprintf('"%s"', fullfile(dspaceroot, 'Compiler', 'X86Tools', 'lib', 'libsupc++.a')), ...   
        sprintf('"%s"', fullfile(dspaceroot, 'Compiler', 'X86Tools', 'lib', 'libstlport.a')) };    
end                                                                                                           
